snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
            logging: '%kernel.debug%'
        #doctrine:
        #    type: predis
        #    alias: doctrine
        #    dsn: "%env(REDIS_URL)%"
        #    logging: '%kernel.debug%'
    #doctrine:
    #    metadata_cache:
    #        client: doctrine
    #        entity_manager: default
    #        document_manager: default
    #        namespace: 'dmc:'
    #    result_cache:
    #        client: doctrine
    #        entity_manager: [default, read]
    #        namespace: 'drc:'
    #    query_cache:
    #        client: doctrine
    #        entity_manager: default
    #        namespace: 'dqc:'
    #    second_level_cache:
    #        client: doctrine
    #        entity_manager: default
    #        namespace: 'dslc:'
