version: "3"
services:
  yarn:
    image: node:10-slim
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - yarn-cache:/web/.cache/yarn/v1
    entrypoint: yarn

volumes:
  yarn-cache: