name: PHP Composer

on:
  push:
    branches: [ master, feature/git-actions-flow-testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        php-versions: ['7.3']

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: php code style
      run: ./vendor/bin/php-cs-fixer fix --dry-run --show-progress=dots --verbose src/

    - name: run test
      run: ./vendor/bin/phpunit

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
